language: perl
perl:
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"
install:
    - cpanm --verbose --installdeps .
script:
    - perl Makefile.PL
    - make
    - make test
    - make install
    - make clean
