---
name: Lingua-Stem-Snowball-Ca
version: 0.01
author:
  - 'Linas Valiukas <linas dot valiukas at gmail dot com>'
  - 'Marvin Humphrey <marvin at rectangular dot com>'
  - 'Israel Olalla of iSOCO <iolalla at isoco dot com>'
abstract: Perl interface to Snowball stemmer for the Catalan language.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  perl: 5.6.2
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 0
provides:
  Lingua::Stem::Snowball::Ca:
    file: lib/Lingua/Stem/Snowball/Ca.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
